In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as mt

In [2]:
''' (1) How to Creating a 3x3 Identity Matrix with Float Data Type? '''

identity_matrix = np.identity(3, dtype=float)
print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [3]:
''' (2) Create a 1D Array with Random Values between 0 and 1. '''

length = 10
random_array = np.random.random(length)
print(random_array)


[0.82643253 0.02816662 0.16884932 0.20730212 0.39137109 0.38656661
 0.78823893 0.06228742 0.27409917 0.47201762]


In [5]:
''' (3) Create a 2D Array with Random Integer Values. '''

import random
rows = 3
cols = 3
random_array = [[random.randint(0, 9) for _ in range(cols)] for _ in range(rows)]
for row in random_array:
    print(row)

[8, 6, 8]
[9, 0, 7]
[7, 3, 7]


In [6]:
''' (4) Creating an Array Using a Custom Function.'''

import numpy as np

def custom_function(i, j):
    return i * j
rows, cols = 3, 4
array = np.empty((rows, cols), dtype=int)
for i in range(rows):
    for j in range(cols):
        array[i, j] = custom_function(i, j)

print(array)


[[0 0 0 0]
 [0 1 2 3]
 [0 2 4 6]]


In [7]:
''' (5) Reshaping a 1D Array into a 2D Array '''

array_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
new_shape = (3, 3)
array_2d = array_1d.reshape(new_shape)

print(array_2d)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
''' (6) How to Creating a 3x3 Array of Ones?'''

array_3x3 = np.ones((3, 3), dtype=int)

print(array_3x3)


[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [9]:
''' (7) How to get the common items between two pythons
NumPy? Input:
a = np. array ([1,2,3,2,3,4,3,4,5,6])
b = np. array ([7,2,10,2,7,4,9,4,9,8])
Expected Output:
array ([2, 4])'''


a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
common_items = np.intersect1d(a, b)


print(common_items)


[2 4]


In [11]:
''' (8) From array a remove all items present in
array b Input:
a = np. array ([1,2,3,4,5])
b = np. array ([5,6,7,8,9])
Expected Output:
array ([1,2,3,4]
'''


a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 6, 7, 8, 9])
result = np.setdiff1d(a, b)

print(result)


[1 2 3 4]


In [22]:
''' (9)  Limit the number of items printed in python NumPy array a to a maximum of
6 elements.
a = np. arrange (15)
Expected Output:
array ([ 0, 1, 2, ..., 12, 13, 14] '''

a = np.arange(15)
np.set_printoptions(precision=3, threshold=6, edgeitems=3, suppress=True)
print(a)

[ 0  1  2 ... 12 13 14]


In [23]:
''' (10) rop all nan values from a 1D NumPy
array Input:
np. array ([1,2,3, np.nan,5,6,7, np.nan])
Desired Output:
array ([ 1., 2., 3., 5., 6., 7.])'''

array = np.array([1, 2, 3, np.nan, 5, 6, 7, np.nan])
cleaned_array = array[~np.isnan(array)]

print(cleaned_array)


[1. 2. 3. 5. 6. 7.]


In [24]:
''' (11) uestion: Create a 1D NumPy array of the first 20 natural numbers and a
2D NumPy array of shape (4, 5) with values ranging from 1 to 20.'''

array_1d = np.arange(1, 21)
array_2d = np.arange(1, 21).reshape(4, 5)

print("1D Array:")
print(array_1d)

print("\n2D Array:")
print(array_2d)


1D Array:
[ 1  2  3 ... 18 19 20]

2D Array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [27]:
''' (12)  Question: Given a 3D NumPy array of shape (2, 3, 4), find its shape, size,
number of dimensions, and data type. Change its data type to float64 and verify
the change.
'''

array_3d = np.arange(24).reshape(2, 3, 4)

shape = array_3d.shape
size = array_3d.size
ndim = array_3d.ndim
dtype = array_3d.dtype

print("Original Array:")
print("Shape:", shape)
print("Size:", size)
print("Number of dimensions:", ndim)
print("Data type:", dtype)

array_3d_float = array_3d.astype(np.float64)
print("\nArray after changing data type to float64:")
print("Shape:", array_3d_float.shape)
print("Size:", array_3d_float.size)
print("Number of dimensions:", array_3d_float.ndim)
print("Data type:", array_3d_float.dtype)
print("Array contents:")
print(array_3d_float)

Original Array:
Shape: (2, 3, 4)
Size: 24
Number of dimensions: 3
Data type: int64

Array after changing data type to float64:
Shape: (2, 3, 4)
Size: 24
Number of dimensions: 3
Data type: float64
Array contents:
[[[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]]

 [[12. 13. 14. 15.]
  [16. 17. 18. 19.]
  [20. 21. 22. 23.]]]


In [29]:
''' (13) Question: Reshape a 1D array of 12 elements into a 3x4 2D array and then
flatten it back into a 1D array using ravel (). Verify that the flattened array
matches the original. '''

original_array = np.arange(12)
reshaped_array = original_array.reshape(3, 4)
flattened_array = reshaped_array.ravel()

print("Original 1D Array:")
print(original_array)

print("\nReshaped 3x4 2D Array:")
print(reshaped_array)

print("\nFlattened 1D Array after ravel():")
print(flattened_array)

Original 1D Array:
[ 0  1  2 ...  9 10 11]

Reshaped 3x4 2D Array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Flattened 1D Array after ravel():
[ 0  1  2 ...  9 10 11]


In [32]:
''' (14)  Question: Given two arrays, a = np. array ([1, 2, 3]) and b = np. array ([4,
5, 6]), perform element-wise addition, subtraction, multiplication, and
division. Explain the behavior when dividing by zero'''

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
addition = a + b
subtraction = a - b
multiplication = a * b
division = a / b

print("Addition:")
print(addition)

print("\nSubtraction:")
print(subtraction)

print("\nMultiplication:")
print(multiplication)

print("\nDivision:")
print(division)

c = np.array([1, 2, 0])
d = np.array([4, 5, 6])
division_with_zero = c / d

print("\nDivision with Zero in Numerator:")
print(division_with_zero)


Addition:
[5 7 9]

Subtraction:
[-3 -3 -3]

Multiplication:
[ 4 10 18]

Division:
[0.25 0.4  0.5 ]

Division with Zero in Numerator:
[0.25 0.4  0.  ]


In [33]:
''' (15) Question: Create a 2D array of shape (3, 1) and a 1D array of length 3. Perform
element-wise addition using broadcasting. Explain how broadcasting rules apply
in this scenario.'''


array_2d = np.array([[1], [2], [3]])
array_1d = np.array([10, 20, 30])
result = array_2d + array_1d

print("2D Array (shape (3, 1)):")
print(array_2d)

print("\n1D Array (length 3):")
print(array_1d)

print("\nResult of addition:")
print(result)


2D Array (shape (3, 1)):
[[1]
 [2]
 [3]]

1D Array (length 3):
[10 20 30]

Result of addition:
[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [34]:
''' (16) Question: Generate a random 2D array of integers between 0 and 10. Use
conditional operators to create a Boolean mask identifying elements greater than
5. Replace all elements greater than 5 with the value 5. '''

array_2d = np.random.randint(0, 11, size=(4, 5))

print("Original 2D Array:")
print(array_2d)

mask = array_2d > 5

print("\nBoolean Mask (elements > 5):")
print(mask)

array_2d[mask] = 5

print("\nModified 2D Array (elements > 5 replaced with 5):")
print(array_2d)


Original 2D Array:
[[6 6 9 9 8]
 [8 2 0 7 1]
 [9 7 1 9 0]
 [8 5 6 8 0]]

Boolean Mask (elements > 5):
[[ True  True  True  True  True]
 [ True False False  True False]
 [ True  True False  True False]
 [ True False  True  True False]]

Modified 2D Array (elements > 5 replaced with 5):
[[5 5 5 5 5]
 [5 2 0 5 1]
 [5 5 1 5 0]
 [5 5 5 5 0]]


In [35]:
''' (17)  Question: Given a 4x4 array of random integers, use indexing and slicing
to extract:
o The entire second row
o The last column
o The subarray consisting of the first two rows and first two columns'''

array_4x4 = np.random.randint(0, 10, size=(4, 4))

print("Original 4x4 Array:")
print(array_4x4)

second_row = array_4x4[1, :]
print("\nEntire Second Row:")
print(second_row)

last_column = array_4x4[:, -1]
print("\nLast Column:")
print(last_column)

subarray = array_4x4[:2, :2]
print("\nSubarray (first two rows and first two columns):")
print(subarray)


Original 4x4 Array:
[[8 6 9 5]
 [7 0 6 4]
 [8 1 5 8]
 [6 9 0 5]]

Entire Second Row:
[7 0 6 4]

Last Column:
[5 4 8 5]

Subarray (first two rows and first two columns):
[[8 6]
 [7 0]]


In [38]:
''' (18) Question: Describe a practical example where NumPy can be used in EDA,
AI, ML, and DL, and implement a NumPy solution for a simple task in each
area. '''

#1 EDA

data = np.array([12, 15, 14, 10, 18, 21, 14, 13, 16, 19])
mean = np.mean(data)
median = np.median(data)
std_dev = np.std(data)

print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)

#2 AI

data = np.array([[100, 2000, 3], [200, 4000, 6], [300, 6000, 9]])
min_vals = np.min(data, axis=0)
max_vals = np.max(data, axis=0)
normalized_data = (data - min_vals) / (max_vals - min_vals)

print("Normalized Data:")
print(normalized_data)

#3 ML

X = np.array([[1], [2], [3], [4]])
X_poly = np.hstack([X, X**2])

print("Original Features:")
print(X)
print("Polynomial Features:")
print(X_poly)

#4 DL

data = np.random.randn(10, 4)
batch_size = 3
num_batches = data.shape[0] // batch_size
batches = np.array_split(data, num_batches)

print("Data Batches:")
for i, batch in enumerate(batches):
    print(f"Batch {i + 1}:")
    print(batch)


Mean: 15.2
Median: 14.5
Standard Deviation: 3.1874754901018454
Normalized Data:
[[0.  0.  0. ]
 [0.5 0.5 0.5]
 [1.  1.  1. ]]
Original Features:
[[1]
 [2]
 [3]
 [4]]
Polynomial Features:
[[ 1  1]
 [ 2  4]
 [ 3  9]
 [ 4 16]]
Data Batches:
Batch 1:
[[ 0.21  -1.251 -0.983  0.648]
 [ 1.293 -1.491 -0.526  0.373]
 [-1.125 -1.156 -0.591  0.594]
 [-0.208  1.032 -2.329 -0.406]]
Batch 2:
[[-0.097 -0.713  0.348 -0.161]
 [ 0.084  0.437  0.22  -0.483]
 [-0.143  0.459  0.741  0.129]]
Batch 3:
[[ 0.835  1.088  0.438  0.949]
 [-0.377  0.82  -1.308  0.119]
 [ 1.074  1.199 -1.174 -0.047]]


In [39]:
''' (19) Question: Create a random 4x4 matrix and use NumPy to compute its
eigenvalues and eigenvectors. Verify the eigenvalues by reconstructing the
matrix.'''

matrix = np.random.rand(4, 4)

print("Original 4x4 Matrix:")
print(matrix)

eigenvalues, eigenvectors = np.linalg.eig(matrix)

print("\nEigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)

eigenvalues_diag = np.diag(eigenvalues)
reconstructed_matrix = eigenvectors @ eigenvalues_diag @ np.linalg.inv(eigenvectors)

print("\nReconstructed Matrix:")
print(reconstructed_matrix)

print("\nMatrix reconstruction is correct:", np.allclose(matrix, reconstructed_matrix))


Original 4x4 Matrix:
[[0.144 0.555 0.259 0.362]
 [0.046 0.159 0.975 0.407]
 [0.864 0.841 0.296 0.95 ]
 [0.83  0.574 0.789 0.627]]

Eigenvalues:
[ 2.22 +0.j    -0.22 +0.226j -0.22 -0.226j -0.554+0.j   ]

Eigenvectors:
[[-0.293+0.j    -0.408+0.397j -0.408-0.397j -0.451+0.j   ]
 [-0.416+0.j    -0.281-0.472j -0.281+0.472j  0.554+0.j   ]
 [-0.612+0.j    -0.014+0.1j   -0.014-0.1j   -0.559+0.j   ]
 [-0.605+0.j     0.603+0.j     0.603-0.j     0.421+0.j   ]]

Reconstructed Matrix:
[[0.144-0.j 0.555+0.j 0.259-0.j 0.362-0.j]
 [0.046-0.j 0.159+0.j 0.975-0.j 0.407-0.j]
 [0.864-0.j 0.841+0.j 0.296-0.j 0.95 -0.j]
 [0.83 +0.j 0.574+0.j 0.789+0.j 0.627-0.j]]

Matrix reconstruction is correct: True


In [43]:
''' (20) Question: Create a 1D array of 27 elements and reshape it into a 3x3x3
3D array. Flatten it back into a 1D array and compare the flattened array
with the original'''

array_1d = np.arange(27)
print(array_1d)
array_3d = array_1d.reshape((3, 3, 3))

print("3D Array:")
print(array_3d)

flattened_array = array_3d.ravel()

print("\nFlattened 1D Array:")
print(flattened_array)

[ 0  1  2 ... 24 25 26]
3D Array:
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]

Flattened 1D Array:
[ 0  1  2 ... 24 25 26]


In [4]:
''' (21) Question: Perform matrix multiplication of two 2D arrays using np.dot ()
and @. Compare the results and performance of both methods using a large
dataset. '''

import time
n = 1000
A = np.random.rand(n, n)
B = np.random.rand(n, n)

start_time = time.time()
result_dot = np.dot(A, B)
end_time = time.time()
time_dot = end_time - start_time

start_time = time.time()
result_at = A @ B
end_time = time.time()
time_at = end_time - start_time

print(f"Matrix multiplication using np.dot() took {time_dot:.4f} seconds.")
print(f"Matrix multiplication using @ took {time_at:.4f} seconds.")


Matrix multiplication using np.dot() took 0.0655 seconds.
Matrix multiplication using @ took 0.0839 seconds.


In [8]:
''' (22) Question: Create a 3D array of shape (2, 1, 4) and a 2D array of shape (4,
1). Perform an element-wise operation using broadcasting and explain the
result. Use np. new axis to achieve the same result without broadcasting.'''


A = np.array([[[1, 2, 3, 4]],
              [[5, 6, 7, 8]]])
B = np.array([[10],
              [20],
              [30],
              [40]])
result_broadcasting = A + B.T
B_expanded = B.T[np.newaxis, :, :]

print("Result with broadcasting:\n", result_broadcasting)
print("Result with np.newaxis:\n", result_no_broadcasting)

Result with broadcasting:
 [[[11 22 33 44]]

 [[15 26 37 48]]]
Result with np.newaxis:
 [[[11 22 33 44]]

 [[15 26 37 48]]]


In [9]:
''' (23) Question: Generate a 2D array of random floats between 0 and 1. Use
conditional operators to create a Boolean mask for values less than 0.5.
Replace these values with their squares and leave the rest unchanged. '''

array = np.random.rand(5, 5)

print("Original Array:\n", array)
mask = array < 0.5
array[mask] = array[mask] ** 2

print("Modified Array:\n", array)


Original Array:
 [[0.6241449  0.85878065 0.72300519 0.1660068  0.05432613]
 [0.38787979 0.40981941 0.82227722 0.71653032 0.52804085]
 [0.47227001 0.73744815 0.31850659 0.88936461 0.18776717]
 [0.98471176 0.54013902 0.2320736  0.61380322 0.43349388]
 [0.76252271 0.41098495 0.56358678 0.17492953 0.78940351]]
Modified Array:
 [[0.6241449  0.85878065 0.72300519 0.02755826 0.00295133]
 [0.15045073 0.16795195 0.82227722 0.71653032 0.52804085]
 [0.22303896 0.73744815 0.10144644 0.88936461 0.03525651]
 [0.98471176 0.54013902 0.05385815 0.61380322 0.18791694]
 [0.76252271 0.16890863 0.56358678 0.03060034 0.78940351]]


In [10]:
''' (24) Question: Given a 5x5 array of sequential integers, use slicing to:
o Extract the diagonal elements
o Replace the elements of the middle row with zeros
o Flip the array vertically and horizontally'''

array = np.arange(25).reshape(5, 5)
print("Original Array:\n", array)

diagonal_elements = np.diagonal(array)
print("Diagonal Elements:\n", diagonal_elements)

array[2, :] = 0
print("Array with Middle Row Zeros:\n", array)

flipped_array = array[::-1, ::-1]
print("Flipped Array:\n", flipped_array)


Original Array:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Diagonal Elements:
 [ 0  6 12 18 24]
Array with Middle Row Zeros:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [ 0  0  0  0  0]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Flipped Array:
 [[24 23 22 21 20]
 [19 18 17 16 15]
 [ 0  0  0  0  0]
 [ 9  8  7  6  5]
 [ 4  3  2  1  0]]


In [11]:
''' (25) Question: Create a 4D array of shape (2, 3, 4, 5) with random integers.
Use advanced slicing to extract a subarray and compute the mean along a
specified axis. '''

array_4d = np.random.randint(0, 10, size=(2, 3, 4, 5))
print("Original 4D Array:\n", array_4d)

subarray = array_4d[0, 1:3, :, :]
print("Extracted Subarray:\n", subarray)

mean_along_axis2 = np.mean(subarray, axis=2)
print("Mean Along Axis 2:\n", mean_along_axis2)


Original 4D Array:
 [[[[3 7 9 3 1]
   [3 3 4 1 0]
   [9 9 2 1 6]
   [2 8 5 2 2]]

  [[6 3 3 0 4]
   [1 3 1 9 4]
   [2 2 9 4 4]
   [9 8 0 8 7]]

  [[9 0 1 2 0]
   [4 6 3 4 1]
   [2 1 5 2 9]
   [5 3 6 9 3]]]


 [[[6 6 9 6 3]
   [6 5 2 1 0]
   [0 0 6 3 0]
   [8 9 5 5 4]]

  [[9 5 1 0 4]
   [5 2 2 7 6]
   [3 4 3 6 6]
   [0 4 4 3 8]]

  [[7 2 6 9 8]
   [2 1 5 0 7]
   [4 2 5 0 7]
   [5 3 1 8 5]]]]
Extracted Subarray:
 [[[6 3 3 0 4]
  [1 3 1 9 4]
  [2 2 9 4 4]
  [9 8 0 8 7]]

 [[9 0 1 2 0]
  [4 6 3 4 1]
  [2 1 5 2 9]
  [5 3 6 9 3]]]
Mean Along Axis 2:
 [[3.2 3.6 4.2 6.4]
 [2.4 3.6 3.8 5.2]]


In [13]:
''' (26) Question: Given an array of shape (10, 20), reshape it to (20, 10) and (5,
40). Discuss the impact on the array's shape, size, and dimensionality. '''

array = np.arange(200).reshape(10, 20)
print(array)

# Reshape to (20, 10)
reshaped_array_1 = array.reshape(20, 10)

print("Reshaped Array (20, 10):\n", reshaped_array_1)
print("Shape:", reshaped_array_1.shape)
print("Size:", reshaped_array_1.size)
print("Dimensionality:", reshaped_array_1.ndim)

# Reshape to (5, 40)
reshaped_array_2 = array.reshape(5, 40)

print("Reshaped Array (5, 40):\n", reshaped_array_2)
print("Shape:", reshaped_array_2.shape)
print("Size:", reshaped_array_2.size)
print("Dimensionality:", reshaped_array_2.ndim)

[[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
   18  19]
 [ 20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37
   38  39]
 [ 40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57
   58  59]
 [ 60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77
   78  79]
 [ 80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97
   98  99]
 [100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
  118 119]
 [120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
  138 139]
 [140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157
  158 159]
 [160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177
  178 179]
 [180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
  198 199]]
Reshaped Array (20, 10):
 [[  0   1   2   3   4   5   6   7   8   9]
 [ 10  11  12  13  14  15  16  17  18  19]
 [ 20  21  22  23  24  25  26  27  28

In [14]:
''' (27) Question: Generate a large 2D array and demonstrate the use of np. reshape
() and unravel () to manipulate its shape for various linear algebra operations. '''

rows, cols = 1000, 1000
large_array = np.arange(rows * cols).reshape(rows, cols)

print("Original 2D Array Shape:", large_array.shape)

reshaped_array_1 = large_array.reshape((2000, 500))
reshaped_array_2 = large_array.reshape((10, 100, 1000))

print("Reshaped Array (2000, 500):", reshaped_array_1.shape)
print("Reshaped Array (10, 100, 1000):", reshaped_array_2.shape)

flattened_array = large_array.ravel()
print("Flattened Array Shape:", flattened_array.shape)

restored_array = flattened_array.reshape(rows, cols)
print("Restored Array Shape:", restored_array.shape)

matrix_1 = np.random.rand(500, 1000)
matrix_2 = np.random.rand(1000, 500)

reshaped_matrix_1 = matrix_1.reshape(1000, 500)
reshaped_matrix_2 = matrix_2.reshape(500, 1000)

result_matrix = np.dot(reshaped_matrix_1, reshaped_matrix_2)

print("Result Matrix Shape:", result_matrix.shape)


Original 2D Array Shape: (1000, 1000)
Reshaped Array (2000, 500): (2000, 500)
Reshaped Array (10, 100, 1000): (10, 100, 1000)
Flattened Array Shape: (1000000,)
Restored Array Shape: (1000, 1000)
Result Matrix Shape: (1000, 1000)


In [16]:
''' (28) Question: Given a 6x6 matrix, use advanced indexing and slicing to extract
the upper triangular part of the matrix and set the lower triangular part to zero.
Verify the result.
'''

matrix = np.arange(1, 37).reshape(6, 6)
print("Original 6x6 Matrix:\n", matrix)

upper_triangular = np.triu(matrix)
print("Upper Triangular Part:\n", upper_triangular)

lower_triangular_zeroed = np.triu(matrix)
print("Matrix with Lower Triangular Part Set to Zero:\n", lower_triangular_zeroed)

lower_triangular_zeroed_manual = matrix.copy()
lower_triangular_zeroed_manual[np.tril_indices_from(lower_triangular_zeroed_manual, -1)] = 0
print("Manually Zeroed Lower Triangular Part Matrix:\n", lower_triangular_zeroed_manual)

print("Verification (Are the matrices equal?):", np.array_equal(lower_triangular_zeroed, lower_triangular_zeroed_manual))


Original 6x6 Matrix:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
Upper Triangular Part:
 [[ 1  2  3  4  5  6]
 [ 0  8  9 10 11 12]
 [ 0  0 15 16 17 18]
 [ 0  0  0 22 23 24]
 [ 0  0  0  0 29 30]
 [ 0  0  0  0  0 36]]
Matrix with Lower Triangular Part Set to Zero:
 [[ 1  2  3  4  5  6]
 [ 0  8  9 10 11 12]
 [ 0  0 15 16 17 18]
 [ 0  0  0 22 23 24]
 [ 0  0  0  0 29 30]
 [ 0  0  0  0  0 36]]
Manually Zeroed Lower Triangular Part Matrix:
 [[ 1  2  3  4  5  6]
 [ 0  8  9 10 11 12]
 [ 0  0 15 16 17 18]
 [ 0  0  0 22 23 24]
 [ 0  0  0  0 29 30]
 [ 0  0  0  0  0 36]]
Verification (Are the matrices equal?): True
